config/routes.rb
Rails.application.routes.draw do

  # get "cocktails/new", to: "cocktails#new"
  # post "cocktails", to: "cocktails#create"

  # get "cocktails", to: "cocktails#index"
  # get "cocktails/:id", to: "cocktails#show"

  # get "cocktails/:id/doses/new", to: "cocktails#edit"
  # post "cocktails/:id/doses", to: "cocktails#update"

  resources :cocktails, only: [:show, :index, :new, :create] do
    resources :doses, only: [:create]
  end
  root "cocktails#index"

  mount Attachinary::Engine => "/attachinary"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_attachment :photo

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail_id, :ingredient_id, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  # before_action :get_cocktail, only: [:show, :edit]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  # def get_cocktail
  #   @cocktail = Cocktail.find(params[:id])
  # end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_cocktail_card.html.erb
<div class="card text-center">

    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(255,255,255,0.5)), url('<%= cl_image_path cocktail.photo.path  %>');">
        <%= link_to "", cocktail_path(cocktail), :class => "card-link" %>
        <div class="card-category"></div>
        <div class="card-description">
        <h3> <%= cocktail.name %> </h3>
        </div>

      </div>


</div>

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name, placeholder: "Sex on the Bitume" %>
  <%= f.input :photo, as: :attachinary %>
  <%= f.button :submit, class: "btn btn-primary"  %>
<% end %>

app/views/cocktails/index.html.erb
<h1 class="text-center">Alcohol is a perfect solvent</h1>
<h3>It dissolves marriages, families and careers </h3>

<div class="container">
  <div class="row">
    <% @cocktails.each do |c| %>
      <div class="col-xs-12 col-sm-4 margin-light">
        <%= render 'cocktail_card', cocktail: c %>
      </div>
    <% end %>
  </div>
</div>

<div class="text-center padded-light">
  <%= link_to "Create a cocktail", new_cocktail_path, class: "btn btn-primary" %>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>New Cocktail</h1>
      <%= render 'form' %>
      <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1><%= @cocktail.name %></h1>

      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @cocktail.photo.path  %>');">

      </div>

      <h4 class="padded-light">Here are the doses</h4>
       <% @cocktail.doses.each do |dose| %>
      <li><%= dose.description %> - <%= dose.ingredient.name %></li>
      <% end %>

      <h4 class="padded-light">Add crazy doses to <%= @cocktail.name %></h4>

      <%= simple_form_for([@cocktail, @dose]) do |f| %>
        <%= f.error_notification %>
        <%= f.input :description %>
        <%= f.association :ingredient %>
        <%= f.submit 'Add' %>
      <% end %>

     <%= link_to 'Back', cocktails_path, input_html: {class: "padded-light"}  %>



    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %> <!-- Append this after the main `javascript_include_tag`. -->
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div id="main-div">
       <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "cocktails.png", id: "logo" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Cocktails"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">This a dead end </a></li>
        <li><a href="#">This also a dead end</a></li>
        <li><a href="#">This a dead end too</a></li>
      </ul>
    </div>
  </div>
</div>